AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

# Style configurations
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

# Layout configurations
Layout/LineLength:
  Max: 100

Layout/ExtraSpacing:
  Enabled: false

# Metrics configurations
Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "test/**/*"

# Naming configurations
Naming/MethodParameterName:
  MinNameLength: 2